---
title: "Season Split Calculations"
author: "Julian McClellan"
date: "July 8, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(magrittr)

knitr::opts_chunk$set(message = FALSE, echo = FALSE)

theme_set(theme_minimal())

EXP_DAT <- read_csv("raw_fdowns_nscore_half_and_reset.csv")
KOFF <- EXP_DAT %>%
  filter(Follow_Kickoff == 1)
```


```{r}
koff_sample <- list(full = KOFF,
               `2000-2010` = KOFF %>%
                 filter(Season <= 2010),
               `2011-2015` = KOFF %>%
                 filter(Season >= 2011 & Season <= 2015),
               `2016` = KOFF %>%
                 filter(Season == 2016)
)

calc_prob_ko <- function(data, to_score, perct = FALSE){
  if (to_score == "off"){
    score_ind <- 1
  } else if (to_score == "def"){
    score_ind <- -1
  } else if (to_score == "none"){
    score_ind <- 0
  }
  frac <- data %>% 
    mutate(o_koff = ifelse(Reset_Team_to_Score == score_ind, 1, 0)) %$%
    mean(o_koff)
  if (perct){
    frac * 100
  } else {
    frac     
  }
}


calc_enp_ko <- function(data, to_score, to = "reset"){
  if (to_score == "off"){
    score_ind <- 1
  } else if (to_score == "def"){
    score_ind <- -1
  } else if (to_score == "none"){
    score_ind <- 0
  }
  if (to == "reset"){
  (points <- data %>%
    filter(Reset_Team_to_Score == score_ind) %$%
    mean(Net_Score_to_Reset))
  } else if (to == "half"){
  (points <- data %>%
    filter(Reset_Team_to_Score == score_ind) %$%
    mean(Net_Score_to_Half))
  }
}

calc_vok_avg <- function(data){
  data %$%
    mean(Net_Score_to_Half)
}

calc_vok_rec <- function(data){
  ko_P_o <- calc_prob_ko(data, "off")
  ko_P_d <- calc_prob_ko(data, "def")
  
  ko_enp_o_oscore_yd <- calc_enp_ko(data, "off")
  ko_enp_o_dscore_yd <- calc_enp_ko(data, "def")
  ko_enp_o_noscore_yd <- calc_enp_ko(data, "none")
  (V_k_rec <- (ko_P_o * ko_enp_o_oscore_yd +
              ko_P_d * (ko_enp_o_dscore_yd) +
              (1 - ko_P_o - ko_P_d) * ko_enp_o_noscore_yd) /
              (1 + ko_P_o - ko_P_d))
}

calc_nobs_ko <- function(data, to_score){
  if (to_score == "off"){
    score_ind <- 1
  } else if (to_score == "def"){
    score_ind <- -1
  } else if (to_score == "none"){
    score_ind <- 0
  } else if (to_score == "all"){
    score_ind <- c(-1, 0, 1)
  }
  data %>%
    filter(Reset_Team_to_Score %in% score_ind) %>%
    nrow()
}

results <- tibble(sample = names(koff_sample),
                  PROBO_KO = koff_sample %>% map(~calc_prob_ko(., "off", TRUE)),
                  PROBD_KO = koff_sample %>% map(~calc_prob_ko(., "def", TRUE)),
                  PROBX_KO = koff_sample %>% map(~calc_prob_ko(., "none", TRUE)),
                  ENPO_KO = koff_sample %>% map(~calc_enp_ko(., "off")),
                  ENPD_KO = koff_sample %>% map(~calc_enp_ko(., "def")),
                  ENPX_KO = koff_sample %>% map(~calc_enp_ko(., "none")),
                  VOK_avg = koff_sample %>% map(~calc_vok_avg(.)),
                  VOK_rec = koff_sample %>% map(~calc_vok_rec(.)),
                  ExpNetPtsO_KO = koff_sample %>% map(~calc_enp_ko(., "off", to = "half")),
                  ExpNetPtsD_KO = koff_sample %>% map(~calc_enp_ko(., "def", to = "half")),
                  ExpNetPtsX_KO = koff_sample %>% map(~calc_enp_ko(., "none", to = "half")),
                  nobs_ko_chk = koff_sample %>% map(~calc_nobs_ko(., "all")),
                  nobso_ko = koff_sample %>% map(~calc_nobs_ko(., "off")),
                  nobsd_ko = koff_sample %>% map(~calc_nobs_ko(., "def")),
                  nobsx_ko = koff_sample %>% map(~calc_nobs_ko(., "none"))
                  )

kable(results[,1:8])
kable(results[,9:16])
```