---
title: "Method 2 | Formula Approach"
author: "Julian McClellan"
date: "August 11th Data Used"
output: pdf_document
---


# Expected Net Points

```{r setup, include=T, message = F, warning = F, echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
source("../utility_funcs.R")
source("form_m2_funcs.R")
theme_set(theme_minimal())

plot_dat <- make_plot_dat(EXP_DAT, 2, "f")
csv_dat <- make_csv_dat(EXP_DAT, 2, "f")

facet_names <- c("", "", "", "")
names(facet_names) <- unique(plot_dat$split)

(
  ggplot(plot_dat) +
  geom_line(aes(x = Yfog, y = enp_fm2, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Expected Net Points Until Half",
       title = "Expected Net Points Until Half",
       subtitle = "Formula Approach | Method 2",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) #+
  # facet_wrap(~ split, labeller = as_labeller(facet_names))
  )

```

# Components

```{r components}
components_plot_dat <- make_plot_dat(EXP_DAT, 2, "f", components = T) %>%
  mutate(split = as.character(split))
components_csv_dat <- make_csv_dat(EXP_DAT, 2, "f", components = T)

enp_dscore <- components_plot_dat %>%
  filter(grepl("comp_enp_o_dscore", split))
enp_oscore <- components_plot_dat %>%
  filter(grepl("comp_enp_o_oscore", split))
enp_noscore <- components_plot_dat %>%
  filter(grepl("comp_enp_o_nscore", split))

p_o <- components_plot_dat %>%
  filter(grepl("comp_P_o", split))
p_d <- components_plot_dat %>%
  filter(grepl("comp_P_d", split))
p_n <- components_plot_dat %>%
  filter(grepl("comp_P_n", split))

# Enp with offense scoring
facet_names <- c("", "", "", "")
names(facet_names) <- unique(enp_oscore$split)

# Get order right
enp_oscore <- within(enp_oscore, split <- 
                           factor(split, levels = names(facet_names)))

ggplot(enp_oscore) +
geom_line(aes(x = Yfog, y = comp_fm2, color = split)) +
labs(x = "Yards from Own Goal",
     y = "Expected Net Points Until Half",
     title = "Expected Net Points Until Half | Offense Scores TD/FG",
     subtitle = "Formula Approach | Method 2",
     color = "Season Split") +
scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                              "2011 - 2015", "2016"),
                   values = c("red", "black", "blue", "green")) # +
# facet_wrap(~ split, labeller = as_labeller(facet_names))


# Enp with defense scoring
facet_names <- c("", "", "", "")
names(facet_names) <- unique(enp_dscore$split)

# Get order right
enp_dscore <- within(enp_dscore, split <- 
                           factor(split, levels = names(facet_names)))

(
  ggplot(enp_dscore) +
  geom_line(aes(x = Yfog, y = comp_fm2, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Expected Net Points Until Half",
       title = "Expected Net Points Until Half | Defense Scores TD/FG",
       subtitle = "Formula Approach | Method 2",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) # +
  # facet_wrap(~ split, labeller = as_labeller(facet_names))
  )


# Enp with no one scoring
facet_names <- c("", "", "", "")
names(facet_names) <- unique(enp_noscore$split)

# Get order right
enp_noscore <- within(enp_noscore, split <- 
                           factor(split, levels = names(facet_names)))

(
  ggplot(enp_noscore) +
  geom_line(aes(x = Yfog, y = comp_fm2, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Expected Net Points Until Half",
       title = "Expected Net Points Until Half | No One Scores TD/FG",
       subtitle = "Formula Approach | Method 2",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) # +
  # facet_wrap(~ split, labeller = as_labeller(facet_names))
  ) 

############################# 
######### Probability #######
#############################

# P of offense scoring
facet_names <- c("", "", "", "")
names(facet_names) <- unique(p_o$split)

# Get order right
p_o <- within(p_o, split <- 
                           factor(split, levels = names(facet_names)))

(
  ggplot(p_o) +
  geom_line(aes(x = Yfog, y = comp_fm2, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Probability",
       title = "Prob of Offense Scroing TD/FG Before Half",
       subtitle = "Formula Approach | Method 2",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) # +
  # facet_wrap(~ split, labeller = as_labeller(facet_names))
  ) 

# P of defense scoring
facet_names <- c("", "", "", "")
names(facet_names) <- unique(p_d$split)

# Get order right
p_d <- within(p_d, split <- 
                           factor(split, levels = names(facet_names)))

(
  ggplot(p_d) +
  geom_line(aes(x = Yfog, y = comp_fm2, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Probability",
       title = "Prob of Defense Scroing TD/FG Before Half",
       subtitle = "Formula Approach | Method 2",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) # +
  # facet_wrap(~ split, labeller = as_labeller(facet_names))
  ) 


# P of no one scoring
facet_names <- c("", "", "", "")
names(facet_names) <- unique(p_n$split)

# Get order right
p_n <- within(p_n, split <- 
                           factor(split, levels = names(facet_names)))

  ggplot(p_n) +
  geom_line(aes(x = Yfog, y = comp_fm2, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Probability",
       title = "Prob of Defense Scroing TD/FG Before Half",
       subtitle = "Formula Approach | Method 2",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) # +
  # facet_wrap(~ split, labeller = as_labeller(facet_names))

```

# Non-Yfog Components Table

```{r ko_table}
library(knitr)
KOFF <- EXP_DAT %>%
  filter(Follow_Kickoff == 1)

koff_sample <- list(`2000-2016` = KOFF,
               `2000-2010` = KOFF %>%
                 filter(Season <= 2010),
               `2011-2015` = KOFF %>%
                 filter(Season >= 2011 & Season <= 2015),
               `2016` = KOFF %>%
                 filter(Season == 2016)
)

calc_prob_ko <- function(data, to_score, perct = FALSE){
  if (to_score == "off"){
    score_ind <- 1
  } else if (to_score == "def"){
    score_ind <- -1
  } else if (to_score == "none"){
    score_ind <- 0
  }
  frac <- data %>% 
    mutate(o_koff = ifelse(Reset_Team_to_Score == score_ind, 1, 0)) %$%
    mean(o_koff)
  if (perct){
    frac * 100
  } else {
    frac     
  }
}


calc_enp_ko <- function(data, to_score, to = "reset"){
  if (to_score == "off"){
    score_ind <- 1
  } else if (to_score == "def"){
    score_ind <- -1
  } else if (to_score == "none"){
    score_ind <- 0
  }
  if (to == "reset"){
  (points <- data %>%
    filter(Reset_Team_to_Score == score_ind) %$%
    mean(Net_Score_to_Reset))
  } else if (to == "half"){
  (points <- data %>%
    filter(Reset_Team_to_Score == score_ind) %$%
    mean(Net_Score_to_Half))
  }
}

calc_vok_avg <- function(data){
  data %$%
    mean(Net_Score_to_Half)
}

calc_vok_rec <- function(data){
  ko_P_o <- calc_prob_ko(data, "off")
  ko_P_d <- calc_prob_ko(data, "def")
  
  ko_enp_o_oscore_yd <- calc_enp_ko(data, "off")
  ko_enp_o_dscore_yd <- calc_enp_ko(data, "def")
  ko_enp_o_noscore_yd <- calc_enp_ko(data, "none")
  (V_k_rec <- (ko_P_o * ko_enp_o_oscore_yd +
              ko_P_d * (ko_enp_o_dscore_yd) +
              (1 - ko_P_o - ko_P_d) * ko_enp_o_noscore_yd) /
              (1 + ko_P_o - ko_P_d))
}

calc_nobs_ko <- function(data, to_score){
  if (to_score == "off"){
    score_ind <- 1
  } else if (to_score == "def"){
    score_ind <- -1
  } else if (to_score == "none"){
    score_ind <- 0
  } else if (to_score == "all"){
    score_ind <- c(-1, 0, 1)
  }
  data %>%
    filter(Reset_Team_to_Score %in% score_ind) %>%
    nrow()
}

results <- tibble(sample = names(koff_sample),
                  PROBO_KO = koff_sample %>% map(~calc_prob_ko(., "off", TRUE)),
                  PROBD_KO = koff_sample %>% map(~calc_prob_ko(., "def", TRUE)),
                  PROBX_KO = koff_sample %>% map(~calc_prob_ko(., "none", TRUE)),
                  ENPO_KO = koff_sample %>% map(~calc_enp_ko(., "off")),
                  ENPD_KO = koff_sample %>% map(~calc_enp_ko(., "def")),
                  ENPX_KO = koff_sample %>% map(~calc_enp_ko(., "none")),
                  VOK_avg = koff_sample %>% map(~calc_vok_avg(.)),
                  VOK_rec = koff_sample %>% map(~calc_vok_rec(.)),
                  ExpNetPtsO_KO = koff_sample %>% map(~calc_enp_ko(., "off", to = "half")),
                  ExpNetPtsD_KO = koff_sample %>% map(~calc_enp_ko(., "def", to = "half")),
                  ExpNetPtsX_KO = koff_sample %>% map(~calc_enp_ko(., "none", to = "half")),
                  nobs_ko_chk = koff_sample %>% map(~calc_nobs_ko(., "all")),
                  nobso_ko = koff_sample %>% map(~calc_nobs_ko(., "off")),
                  nobsd_ko = koff_sample %>% map(~calc_nobs_ko(., "def")),
                  nobsx_ko = koff_sample %>% map(~calc_nobs_ko(., "none"))
                  )

kable(results[,1:8])
kable(results[,9:14])
kable(results[,15:16])
```

# Appendix: Variable Construction Formulas

$$
V_{k} ^ {rec} (M\;2) = \frac{Prob(O\; |\;KO) * ExpPTS_O + Prob(D\;|\;KO) * (- ExpPTS_O) + 
[1 - Prob(O\;|\;KO) - Prob(D\;|\;KO)] * ExpNetPTS}{1 + Prob(O\;|\;KO) - Prob(D\;|\;KO)}
$$

$$
V(yrdline=x) = Prob(O\;|\; yrdline = x) * [(ExpNetPTS_O\; | O\;Score, yrdline = x) - V_k] -
$$
$$
 Prob(D | yrdline = x) * [(-ExpPTS_O\; | D\;Score, yrdline = x) - V_k] + 
$$

$$
[1 - Prob(O|yrdline = x) - Prob(D|yrdline=x)] * (ExpNetPts_O | Not\;TD,\;Not\;FG,yrdline = x)
$$

Similarly except replace $V_k$ with $V_{k} ^ {rec}(Method\;2)$.