---
title: "Method 1 | Regression Approach"
author: "Julian McClellan"
date: "August 11th Data"
output: pdf_document
---
# Expected Net Points

```{r setup, include=T, message=F, warning=F, echo=F}
library(tidyverse)
library(ggplot2)
library(glue)

all <- read.csv("M2_regression_all.csv")
nn <- read.csv("M2_regression_99.csv")
var <- read.csv("M2_regression_var.csv")

v_iv <- nn %>%
  select(v99_iv_clust_2000.2016,
         v99_iv_clust_2000.2010,
         v99_iv_clust_2011.2015)

v_ols <- all %>%
  select(v)

year_start <- 2000
year_stop <- 2016

source_dir <- "../"

D_key = as_tibble(rbind(diag(1, 100, 100), 
          diag(1, 100, 100),
          diag(1, 100, 100)
          )) %>%
  set_names(paste0(rep("D_", 100), 1:100)) %>%
  bind_cols(Yfog = rep(c(1:99, 0), 3), Reset_Team_to_Score = c(rep(-1, 100), 
                                                         rep(0, 100), 
                                                         rep(1, 100)), .)

FDOWN_EXP <- read.csv(glue(
  "{source_dir}correc_raw_fdowns_nscore_half_and_reset.csv")) %>%
  mutate(exp_type = "first_down") %>%
  filter(Season >= year_start, Season <= year_stop)

KOFF_EXP <- read.csv(
  glue("{source_dir}corec_raw_koff_nscore_half_and_reset.csv")) %>%
  mutate(exp_type = "kickoff") %>%
  filter(Season >= year_start, Season <= year_stop)

rv_df <- bind_rows(FDOWN_EXP, KOFF_EXP) %>%
  select(-matches("RUSH|PUNT|FGXP|CONV|PUNT|NOPL|KOFF|PASS|FGXP|ONSD|Armchair_dsq|Drive_num|Drive_start"),
         -X) %>%
  mutate(Yfog = ifelse(is.na(Yfog), 0, Yfog)) %>%
  merge(D_key)

theme_set(theme_minimal())

knitr::opts_chunk$set(echo = F, warning = F, message = F)

plot_dat <- make_plot_dat(rv_df, 1, "r")
csv_dat <- make_csv_dat(rv_df, 1, "r") # Full dat, stacked

FDOWN_EXP <- FDOWN_EXP %>%
  merge(D_key)

KOFF_EXP <- KOFF_EXP %>%
  merge(D_key)

csv_dat <- make_csv_dat(FDOWN_EXP, 1, "r", name = "fdown_only") # Fdown only
csv_dat <- make_csv_dat(KOFF_EXP, 1, "r", name = "koff_only") # Koff only



facet_names <- c("", "", "", "")
names(facet_names) <- unique(plot_dat$split)

(
  ggplot(plot_dat) +
  geom_line(aes(x = Yfog, y = enp_rm1, color = split)) +
  labs(x = "Yards from Own Goal",
       y = "Expected Net Points Until Half",
       title = "Expected Net Points Until Half",
       subtitle = "Regression Approach | Method 1",
       color = "Season Split") +
  scale_color_manual(labels = c("2000 - 2016", "2000 - 2010",
                                "2011 - 2015", "2016"),
                     values = c("red", "black", "blue", "green")) # +
  # facet_wrap(~ split, labeller = as_labeller(facet_names))
  )
```


```{r}
EXP_SPLIT <- season_splits(rv_df)

precision_comp <- bind_rows(
  EXP_SPLIT %>%
    map_df(~ calc_precision(., "Armchair_gid")),
  EXP_SPLIT %>%
    map_df(~ calc_precision(., "Half_num")),
  EXP_SPLIT %>%
    map_df(~ calc_precision(., "Drive_num")),
  EXP_SPLIT %>%
    map_df(~ calc_precision(.))
)

precision_comp_csv <- precision_comp %>%
    transmute(split_and_cluster = glue("{Year}_{Cluster_var}"), 
              Yfog = Yfog,
              SE = SE) %>%
  spread(split_and_cluster, SE) %>%
  select(Yfog, 
         `2000 - 2016_Armchair_gid`,
         `2000 - 2016_Half_num`,
         `2000 - 2016_Drive_num`,
         `2000 - 2016_None`,
         `2000 - 2010_Armchair_gid`,
         `2000 - 2010_Half_num`,
         `2000 - 2010_Drive_num`,
         `2000 - 2010_None`,
         `2011 - 2015_Armchair_gid`,
         `2011 - 2015_Half_num`,
         `2011 - 2015_Drive_num`,
         `2011 - 2015_None`,
         `2016_Armchair_gid`,
         `2016_Half_num`,
         `2016_Drive_num`,
         `2016_None`
         )

write_csv(precision_comp_csv, "enp_rm1_se.csv")
precision_comp <- within(precision_comp, Year <- 
                           factor(Year, levels = c("2000 - 2016", "2000 - 2010",
                                                   "2011 - 2015", "2016")))

(se_plot <- precision_comp %>%
  ggplot(aes(Yfog, SE, color = Cluster_var)) +
    geom_point(size = .1) +
    labs(title = "Clustered Standard Error Comparison",
         subtitle = "Different Seasons") + 
    facet_wrap(~ Year))
```